//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishingHouseV6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Publication = new HashSet<Publication>();
        }
    
        public int IdOrder { get; set; }
        public int IdClient { get; set; }
        public int IdTypeProduction { get; set; }
        public int IdTypography { get; set; }
        public System.DateTime DateRegistration { get; set; }
        public System.DateTime DateRealization { get; set; }
        public bool MarkOfRealization { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TypeProduction TypeProduction { get; set; }
        public virtual Typography Typography { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Publication> Publication { get; set; }
    }
}
